import fs from 'node:fs';

const read = path => fs.readFileSync(path, 'utf8');
const fail = message => {
  console.error(`Smoke check failed: ${message}`);
  process.exitCode = 1;
};
const mustContain = (name, text, needle) => {
  if(!text.includes(needle)) fail(`${name} neobsahuje povinný text: ${needle}`);
};
const mustNotContain = (name, text, needle) => {
  if(text.includes(needle)) fail(`${name} stále obsahuje zakázaný text: ${needle}`);
};

const html = read('index.html');
const app = read('src/app/lifehub-app.js');
const constants = read('src/config/constants.js');
const storage = read('src/storage/indexed-db.js');
const crypto = read('src/security/crypto.js');
const css = read('src/styles/lifehub.css');
const pkg = JSON.parse(read('package.json'));
const manifest = JSON.parse(read('public/manifest.json'));
const sw = read('public/sw.js');
const manual = read('public/manual.html');
const payrollParser = read('src/features/payroll-elanor.js');
const gitignore = read('.gitignore');
const ci = read('.github/workflows/ci.yml');
const deploy = read('.github/workflows/deploy.yml');

mustContain('index.html', html, 'data-action="export-complete-backup"');
mustContain('index.html', html, 'id="backupStatus"');
mustContain('index.html', html, 'id="changeVaultPassword"');
mustContain('index.html', html, 'Oficiální osobní nástroj');
mustContain('index.html', html, 'data-tab="budget"');
mustContain('index.html', html, 'data-tab="groceries"');
mustContain('index.html', html, 'data-tab="ailog"');
mustContain('index.html', html, 'data-tab="rewards"');
mustContain('index.html', html, 'id="printReport"');
mustContain('index.html', html, 'data-tab="garden"');
mustContain('index.html', html, 'data-tab="partner"');
mustContain('index.html', html, 'data-tab="payments"');
mustNotContain('index.html', html, 'id="partnerMergeBtn"');
mustContain('index.html', html, 'id="importPayrollsFile"');
mustContain('index.html', html, 'id="importPayrollPdfBatchBtn"');
mustContain('index.html', html, 'id="paymentAutomatic"');
mustContain('index.html', html, 'id="groceryBulkPreview"');
mustContain('index.html', html, 'class="save-status-row"');
mustContain('index.html', html, 'id="setFamilyPasswordBtn"');
mustContain('index.html', html, 'id="familyPasswordStatus"');
mustContain('lifehub-app.js', app, 'function setFamilyPassword');
mustContain('lifehub-app.js', app, 'familyPassword:textLimit');
mustContain('lifehub-app.js', app, 'SaveLifecycle');
mustContain('lifehub-app.js', app, 'showUnsavedGuard');
mustContain('lifehub-app.js', app, 'exportEmergencyEncryptedBackup');
mustContain('lifehub-app.js', app, 'writeEncryptedStateEnvelope');
mustContain('lifehub-app.js', app, 'function hasLegacyState()');
mustContain('lifehub-app.js', app, 'if(startupStorageError)');
mustContain('lifehub-app.js', app, 'init().catch(error =>');
mustContain('lifehub-app.js', app, 'calculateRegularInstallmentPayment');
mustContain('lifehub-app.js', app, 'buildDataBackupPayload({includeFamilyPassword:false})');
mustContain('lifehub-app.js', app, 'Šifrovaný rodinný soubor byl vytvořen pomocí uloženého rodinného hesla.');
mustContain('lifehub-app.js', app, 'function exportCompleteEncryptedBackup');
mustContain('lifehub-app.js', app, 'function importCompleteBackup');
mustContain('lifehub-app.js', app, 'prepareBackupFileEntries');
mustContain('lifehub-app.js', app, 'recoverPendingRestore');
mustContain('lifehub-app.js', app, 'recoverPendingKeyRotation');
mustContain('lifehub-app.js', app, 'function changeVaultPassword');
mustContain('lifehub-app.js', app, 'offerBackupBeforeImport');
mustContain('lifehub-app.js', app, 'reconcileStoredFileFlags');
mustContain('lifehub-app.js', app, 'buildImportPreviewMessage');
mustContain('lifehub-app.js', app, 'metadata: backupMetadata');
mustContain('lifehub-app.js', app, 'lastRestoreAt');
mustContain('lifehub-app.js', app, 'validateBackupFileSet');
mustContain('lifehub-app.js', app, 'function renderBudget');
mustContain('lifehub-app.js', app, 'function renderGroceries');
mustContain('lifehub-app.js', app, 'function renderAiLog');
mustContain('lifehub-app.js', app, 'function renderRewards');
mustContain('lifehub-app.js', app, 'function printReport');
mustContain('lifehub-app.js', app, 'function showInstallmentDebtOnOpen');
mustContain('lifehub-app.js', app, 'function migrateLegacyGroceries');
mustContain('lifehub-app.js', app, 'function renderGarden');
mustContain('lifehub-app.js', app, 'function renderPartner');
mustContain('lifehub-app.js', app, 'function renderHouseholdPayments');
mustContain('lifehub-app.js', app, 'function reconcileAutomaticHouseholdPayments');
mustContain('lifehub-app.js', app, 'function importPayrollPdfBatch');
mustContain('lifehub-app.js', app, 'function renderGroceryBulkPreview');
mustContain('lifehub-app.js', app, "kpi('Zbývající platby'");
mustNotContain('lifehub-app.js', app, 'function applyFamilyMerge');
mustContain('lifehub-app.js', app, 'Vaše vlastní data se nezměnila');
mustContain('lifehub-app.js', app, 'LifeHub family snapshot');
mustNotContain('lifehub-app.js', app, 'familyDeleted');
mustNotContain('lifehub-app.js', app, 'recordFamilyDeletion');
mustContain('lifehub-app.js', app, 'function importPayrollsJson');
mustContain('lifehub-app.js', app, 'parseElanorPayslip');
mustContain('indexed-db.js', storage, 'idbReplaceEncryptedStores');
mustContain('crypto.js', crypto, 'validateKdfIterations');
mustContain('constants.js', constants, "APP_VERSION = '4.5.2'");
mustContain('service worker', sw, "lifehub-vite-shell-v4-5-2-payroll-1");
mustContain('service worker', sw, 'discoverBuildAssets');
mustContain('service worker', sw, "'./manual.html'");
mustContain('index.html', html, 'id="manualBtn"');
mustContain('index.html', html, 'id="manualFrame"');
mustContain('index.html', html, '>Manuál</span>');
mustContain('manual.html', manual, 'LifeHub – interaktivní manuál');
mustContain('manual.html', manual, 'Uživatelská příručka pro verzi 4.5.2');
mustContain('app', app, 'payroll-primary');
mustContain('app', app, "['cleanPay','Čistá mzda'");
mustContain('parser', payrollParser, "take('cleanPay', 'cleanPay', 'Čistá mzda')");
mustContain('manual.html', manual, 'Ukládání a chyby');
mustContain('manual.html', manual, 'Nouzová šifrovaná záloha');
mustContain('manual.html', manual, 'Výsledky v celém manuálu');
mustContain('manual.html', manual, 'Osmnáct částí');
mustContain('manual.html', manual, 'Hrazeno automaticky z účtu');
mustContain('manual.html', manual, 'Hromadně uložit vybraná PDF');
mustContain('manual.html', manual, 'Nadpisy <code>Lidl:</code>');
mustContain('manual.html', manual, 'lifehub-manual-activity');
mustNotContain('service worker', sw, 'skipWaiting()');
mustNotContain('CSS', css, '.w-100{');
mustContain('.gitignore', gitignore, 'node_modules/');
mustContain('.gitignore', gitignore, '*.pdf');
mustContain('.gitignore', gitignore, '!package.json');
mustContain('ci.yml', ci, 'npm ci');
mustContain('ci.yml', ci, 'npm run check');
mustContain('deploy.yml', deploy, 'npm ci');
mustContain('deploy.yml', deploy, 'npm run check');

if(pkg.version !== '4.5.2') fail('package.json verze není 4.5.2');
if(manifest.name !== 'LifeHub' || manifest.lang !== 'cs' || manifest.scope !== './') fail('manifest nemá produkční metadata LifeHubu 4.3');
if(process.exitCode) process.exit(process.exitCode);
console.log('Smoke check OK: LifeHub 4.5.2 má dominantní čistou mzdu, oddělenou dobírku, přehledné výplatní karty, mobilní navigaci, aktualizovaný manuál, PWA a GitHub workflow.');
